//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessEntities : DbContext
    {
        public FitnessEntities()
            : base("name=FitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<group> groups { get; set; }
        public DbSet<monitoringvisit> monitoringvisits { get; set; }
        public DbSet<subscription> subscriptions { get; set; }
        public DbSet<trainingprogram> trainingprograms { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
    }
}
