//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class group
    {
        public group()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int idGroup { get; set; }

        [Required]
        [Display(Name = "Название группы")]
        public string nameGroup { get; set; }

        public int idTraining { get; set; }
    
        public virtual trainingprogram trainingprogram { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
