//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class monitoringvisit
    {
        public int idVisit { get; set; }

        [Required]
        [Display(Name = "Дата посещения")]
        public System.DateTime dateOfVisit { get; set; }

        public int idUser { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
