//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscription
    {
        public subscription()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int idSubscription { get; set; }
        public int duration { get; set; }
        public System.DateTime dateOfPurchase { get; set; }
        public int idTraining { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual trainingprogram trainingprogram { get; set; }
    }
}
