//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class trainingprogram
    {
        public trainingprogram()
        {
            this.groups = new HashSet<group>();
            this.subscriptions = new HashSet<subscription>();
        }
    
        public int idTraining { get; set; }

        [Required]
        [Display(Name = "Цена")]
        public int price { get; set; }

        [Required]
        [Display(Name = "Тип тренировки")]
        public string typeTraining { get; set; }

        [Required]
        [Display(Name = "Вид тренировки")]
        public string kindTraining { get; set; }
    
        public virtual ICollection<group> groups { get; set; }
        public virtual ICollection<subscription> subscriptions { get; set; }
    }
}
