//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.monitoringvisits = new HashSet<monitoringvisit>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string fullName { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public string email { get; set; }
        public int telephone { get; set; }
        public bool frozen { get; set; }
        public Nullable<int> idGroup { get; set; }
        public Nullable<int> idSubscription { get; set; }
    
        public virtual group group { get; set; }
        public virtual subscription subscription { get; set; }
        public virtual ICollection<monitoringvisit> monitoringvisits { get; set; }
    }
}
